### ISSUE TITLE
testcase in level 4, search function after rollback

### ISSUE THREAD

**Issue by iamamp** [PaulLockett/CodeSignal_Practice_Industry_Coding_Framework#1]
Why is the post rollback search query for "up" returning "Initial.txt" along with "Upload.txt"? the prefix "up" has nothing to do with "Initial", shouldnt be returned on l54 in test_simulation.py

**Comment by PaulLockett** [comment]
Good catch! Could you make a pr? I will approve it.

**Comment by iamamp** [comment]
added

**Comment by PaulLockett** [comment]
pr #2  merged closing this
