### ISSUE TITLE
Noticed some discrepancies between assignment and test

### ISSUE THREAD

**Issue by kevkid** [PaulLockett/CodeSignal_Practice_Industry_Coding_Framework#3]
For example this line in task 1:
https://github.com/PaulLockett/CodeSignal_Practice_Industry_Coding_Framework/blob/main/practice_assessments/file_storage/level1.md?plain=1#L36
asks us to return the size, but in the test:
https://github.com/PaulLockett/CodeSignal_Practice_Industry_Coding_Framework/blob/main/practice_assessments/file_storage/test_simulation.py#L42
it looks for "got Cars.txt"

**Comment by PaulLockett** [comment]
Good point! I think I changed this myself when I practiced. 
Could you make a pr to update this?

**Comment by kevkid** [comment]
Few more notes where I believe them to be incorrect: 
The test for 2. want ascending order instead of descending order?
Test data 3 I think is incorrect?, it should return both python.txt and pythonCopy.txt as there is no ttl in python.txt
similarly, should the last test ["FILE_SEARCH_AT", "2021-07-01T12:00:00", "Code"] return codeCopy as well?

Let me know if these make sense.

**Comment by jlucassen** [comment]
Seconding kevKid, just took this test and can't see any reason that PythonCopy and CodeCopy shouldn't be returned in the FindAt.

**Comment by PaulLockett** [comment]
closed with #4
